name: easy_sync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^11.4.0
  googleapis_auth: ^1.2.0
  google_sign_in: ^6.2.1
<<<<<<< HEAD
  file_picker: ^9.0.0
=======
  http: ^1.3.0
>>>>>>> d579d39 (closes #58 (#59))

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
