name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows support
        run: flutter config --enable-windows-desktop
          
      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter app
      - run: flutter build windows