name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Set Execution Policy for PowerShell
        run: Set-ExecutionPolicy Unrestricted -Scope Process -Force
        shell: pwsh

      - name: Run custom build script
        run: bash .\build.ps1
        shell: pwsh

      - name: Run custom tests
        run: bash .\test.ps1
        shell: pwsh

      - name: Clean build
        run: bash .\clean.ps1
        shell: pwsh
