name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Set Execution Policy for PowerShell
        shell: pwsh
        run: Set-ExecutionPolicy Unrestricted -Scope Process -Force

      - name: Run custom build script
        shell: pwsh
        run: .\build.ps1

      - name: Run custom tests
        shell: pwsh
        run: .\test.ps1

      - name: Clean build
        shell: pwsh
        run: .\clean.ps1
