name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run custom build script
        run: bash ./build.sh

      - name: Run custom tests
        run: bash ./test.sh

      - name: Clean tests
        run: bash ./clean.sh