name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run custom build script
        shell: bash
        run: ./build.sh

      - name: Run custom tests
        shell: bash
        run: ./test.sh

      - name: Clean build
        shell: bash
        run: ./clean.sh
